# Copyright (c) Facebook, Inc. and its affiliates

import argparse

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--train_on_dataset",type=str, default="all", help="")
    parser.add_argument("--output_path", type=str, default="./prediction.json")
    parser.add_argument("--test_type", type=str, default="seen", help="seen, unseen")
    parser.add_argument("--domain_description", type=str, default="false")
    # parser.add_argument("--resume_from_checkpoint", type=str, default="save/t5-smallt5_except_domain_none_slotlang_human_lr_0.0001_epoch_5_seed_557/lightning_logs/version_5/checkpoints/epoch=1.ckpt", help="resume from the checkpoint(including model, optimizer, and hyperparameter ... ")
    parser.add_argument("--resume_from_checkpoint", type=str, default=None, help="resume from the checkpoint(including model, optimizer, and hyperparameter ... ")
    parser.add_argument("--model_checkpoint", type=str, default="t5-small", help="Path, url or short name of the model")
    parser.add_argument("--load_from_checkpoint", type=str, default="epoch=2.ckpt")
    parser.add_argument("--saving_dir", type=str, default="save", help="Path for saving")
    parser.add_argument("--train_batch_size", type=int, default=8, help="Batch size for training")
    parser.add_argument("--meta_batch_size", type=int, default=1, help="Batch size for meta training")
    parser.add_argument("--dev_batch_size", type=int, default=8, help="Batch size for validation")
    parser.add_argument("--test_batch_size", type=int, default=32, help="Batch size for test")
    parser.add_argument("--gradient_accumulation_steps", type=int, default=32, help="Accumulate gradients on several steps")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate")
    parser.add_argument("--max_norm", type=float, default=1.0, help="Clipping gradient norm")
    parser.add_argument("--n_epochs", type=int, default=5, help="Number of training epochs")
    parser.add_argument("--seed", type=int, default=557, help="Random seed")
    parser.add_argument("--verbose", action='store_true', help="continual baseline")
    parser.add_argument("--length", type=int, default=50, help="Batch size for validation")
    parser.add_argument("--max_history", type=int, default=2, help="max number of turns in the dialogue")
    parser.add_argument("--GPU", type=int, default=1, help="number of gpu to use")
    parser.add_argument("--model_name", type=str, default="t5", help="use t5 or bart?")
    parser.add_argument("--slot_lang", type=str, default="human", help="use 'none', 'human', 'naive', 'value', 'question', 'slottype' slot description")
    parser.add_argument("--fewshot", type=float, default=0.0, help="data ratio for few shot experiment")
    parser.add_argument("--fix_label", action='store_true')
    parser.add_argument("--except_domain", type=str, default="none", help="hotel, train, restaurant, attraction, taxi")
    parser.add_argument("--only_domain", type=str, default="none", help="hotel, train, restaurant, attraction, taxi")
    parser.add_argument("--threshold", type=float, default=0.4)
    parser.add_argument("--semi", action='store_true')
    parser.add_argument("--mode", type=str, default="train")
    
    args = parser.parse_args()
    return args
